name: Page Builder by ALMO

on:
  push:
    branches:
      - main
    paths:
      - 'posts/**.md'


permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true


jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
            fetch-depth: 0

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v44
        with:
          files: 'posts/**.md'
          json: true

      - name: Write changed files to output
        id: write-changed-files
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}" > changed_files.json

  setup:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.result == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Git
        run: |
            cd ${{ github.workspace }}
            git config --global user.email "actions@example.com"
            git config --global user.name "GitHub Actions"

      - name: Setup ALMO
        run: |
            git submodule update --init --recursive --remote 

      - name: Compile almo.cpp
        run: |
          cd ALMO
          bash build.sh
      

  build:
    runs-on: ubuntu-latest
    needs: setup
    if: ${{ needs.setup.result == 'success' }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Generate HTML
        run: |
          python3 blog_builder/build.py

      - name: Update RSS
        run: |
          python3 blog_builder/rss.py

      - name: Commit changes
        run: |
          git config pull.rebase false
          git add .
          git commit -m "Update blog"
          
      - name: Push changes
        uses: ad-m/github-push-action@master  
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main  